spring:
  datasource:
    url: jdbc:mysql://mtdbank-db:3306/mtdbank?createDatabaseIfNotExist=true
    username: root
    password: admin
    testWhileIdle: true
    validationQuery: SELECT 1
    
  jpa:
    show-sql: true
    hibernate.ddl-auto: none 
    properties: 
      hibernate:
        format_sql: false
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        id: 
          new_generator_mappings: false
server:
  compression: 
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
    min-response-size: 1024

  